name: flake-bump
on:
  schedule: 
    - cron: '0 5 * * 3'
  workflow_dispatch:


env:
  CACHIX_NAME: ${{ secrets.CACHIX_NAME }}
  CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

jobs:
  flake-bump-and-build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'Rampage'

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Install Cachix
        run: nix profile install nixpkgs#cachix 
      - name: Run flake bump
        id: bump
        run: |
          ./flake-bump.sh
        continue-on-error: true

      - name: Build if flake-bump updated
        if: steps.bump.outputs.changed == 'true'
        run: ./build.sh

      - name: Auto commit updated flake.lock
        if: steps.bump.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump flake.lock
          branch: master
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Bot 
          commit_author: Flake Bot <actions@github.com> 
          skip_dirty_check: false    
          skip_fetch: true
