name: flake-bump
on:
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List repository files
        run: ls -R
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'Holster'
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake update

      - name: Check Changes
        id: check_changes
        run: |
          if git diff --quiet flake.lock; then
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            git diff flake.lock
          fi
      # enable cache and rebuild system if there are changes in flake.lock
      - name: Use Cachix
        uses: cachix/cachix-action@v16
        if: steps.check_changes.outputs.has_changes == 'true'
        with:
          name: "datantho-nixos"
          authToken: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: Verify Configuration
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
           nix build .#nixosConfigurations.zeno.config.system.build.toplevel --no-link
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump flake.lock
          branch: master
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Bot 
          commit_author: Flake Bot <actions@github.com> 
          skip_dirty_check: false    
          skip_fetch: true
