name: flake-bump
on:
  schedule:
    - cron: "0 3 * * 1-5" 
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List repository files
        run: ls -R
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Use Cachix
        uses: cachix/cachix-action@v15
        with:
          name: "datantho-nixos"
          authToken: ${{ secrets.CACHIX_SIGNING_KEY }}
      - run: nix flake update

      - name: Check Changes
        id: check_changes
        run: |
          if git diff --quiet flake.lock; then
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            git diff flake.lock
          fi
      # only rebuild if there is change in flake
      - name: Verify Configuration
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          nix run github:Mic92/nix-fast-build -- --skip-cached --no-nom --eval-max-memory-size 16384 --flake .#nixosConfigurations.zeno.config.system.build.toplevel
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump flake.lock
          branch: master
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Bot 
          commit_author: Flake Bot <actions@github.com> 
          skip_dirty_check: false    
          skip_fetch: true
