name: flake-bump
on:
  schedule: 
    - cron: '0 5 * * 3'
  workflow_dispatch:


env:
  CACHIX_NAME: ${{ secrets.CACHIX_NAME }}
  CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

jobs:
  flake-bump:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_lock.outputs.changed }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Run flake bump
        id: flake_update
        run: ./flake-bump.sh
        continue-on-error: true

  build:
    needs: flake-update
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'Holster'
      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Build everything
        run: ./build-all.sh

  commit:
    needs: [build]
    permissions:
      contents: write
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download flake.lock
        uses: actions/download-artifact@v4
        with:
          name: flake-lock
          path: .

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump flake.lock
          branch: master
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Bot 
          commit_author: Flake Bot <actions@github.com> 
          skip_dirty_check: false    
          skip_fetch: true
