name: flake-bump
on:
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Update flake.lock
        run: nix flake update

      - name: Check for flake.lock changes
        id: check_changes
        run: |
          if git diff --quiet flake.lock; then
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload flake.lock
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: flake-lock
          path: flake.lock

  
  build:
    needs: bump
    if: needs.bump.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [zeno, mark]
    steps:
      - uses: actions/checkout@v4
  
      - name: Download updated flake.lock
        uses: actions/download-artifact@v4
        with:
          name: flake-lock
          path: .
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'Holster'
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
  
      - name: Use Cachix
        uses: cachix/cachix-action@v16
        with:
          name: datantho-nixos
          authToken: ${{ secrets.CACHIX_SIGNING_KEY }}
  
      - name: Build ${{ matrix.target }}
        run: |
          case "${{ matrix.target }}" in
            zeno)
              nix build .#nixosConfigurations.zeno.config.system.build.toplevel --no-link 
              ;;
            mark)
              nix build .#homeConfigurations.mark.activationPackage --no-link 
              ;;
          esac
  commit:
    needs: build
    if: needs.bump.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download flake.lock
        uses: actions/download-artifact@v4
        with:
          name: flake-lock
          path: .

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump flake.lock
          branch: master
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Bot 
          commit_author: Flake Bot <actions@github.com> 
          skip_dirty_check: false    
          skip_fetch: true
