name: flake-check
on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: ["flake-bump"]
    types:
      - completed

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Install Cachix
        run: nix profile install nixpkgs#cachix 
      - name: Run flake check
        run: nix flake check

