name: Gitlab Sync

on: 
  push:
  create:
  delete:
  workflow_dispatch:
  workflow_run:
    workflows: ["flake-bump"]
    types:
      - completed

jobs:
  sync:
    name: Gitlab Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: action-pack/gitlab-sync@v3
        with:
          username: ${{ github.actor }}
          url: https://gitlab.com/${{ github.repository }}.git
          # Personal access token from gitlab.com 
          token: ${{ secrets.GITLAB_TOKEN }}
